# Generated by Django 4.2 on 2023-12-07 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
        ('Loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=60)),
                ('total_amount', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('status', models.SmallIntegerField(default=1)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('custumers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.custumersmodel')),
            ],
            options={
                'db_table': 'payments_payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentsDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('loand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loans.loansmodel')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payments.paymentsmodel')),
            ],
            options={
                'db_table': 'payments_paymentsdetail',
            },
        ),
    ]
