# Generated by Django 4.2 on 2023-12-07 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoansModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=60)),
                ('status', models.SmallIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('contract_version', models.SmallIntegerField(default=1)),
                ('maximum_payment_date', models.DateTimeField(auto_now=True)),
                ('taken_at', models.DateTimeField(auto_now=True)),
                ('outstanding', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('custumers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.custumersmodel')),
            ],
            options={
                'db_table': 'loans_loan',
            },
        ),
    ]
